/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatBubbles: typeof import('./src/components/ChatBubbles.vue')['default']
    ChatWidget: typeof import('./src/components/ChatWidget.vue')['default']
  }
}
